services:
  ultrafeeder:
    image: ${ULTRAFEEDER_CONTAINER}
    tty: true
    container_name: ultrafeeder
    hostname: ultrafeeder
    restart: always
    device_cgroup_rules:
      - 'c 189:* rwm'
    ports:
      - ${_ADSBIM_STATE_TAR1090_PORT:-8080}:80 # to expose the web interface
    environment:
      # --------------------------------------------------
      # general parameters:
      - LOGLEVEL=error
      - TZ=${FEEDER_TZ}
      # --------------------------------------------------
      # SDR related parameters:
      - READSB_DEVICE_TYPE=${FEEDER_RTL_SDR}
      - READSB_RTLSDR_DEVICE=${FEEDER_SERIAL_1090}
      - READSB_RTLSDR_PPM=${ADSB_SDR_PPM}
      - READSB_ENABLE_BIASTEE=${FEEDER_ENABLE_BIASTEE}
      - READSB_AUTOGAIN_INITIAL_GAIN=29.6
      #
      # --------------------------------------------------
      # readsb/decoder parameters:
      - READSB_LAT=${FEEDER_LAT}
      - READSB_LON=${FEEDER_LONG}
      - READSB_ALT=${FEEDER_ALT_M}
      - READSB_GAIN=${FEEDER_READSB_GAIN}
      - READSB_MODEAC=false
      - READSB_RX_LOCATION_ACCURACY=2
      - READSB_STATS_RANGE=true
      # Sources and Aggregator connections:
      # (Note - remove the ones you are not using / feeding)
      - ULTRAFEEDER_CONFIG=${FEEDER_ULTRAFEEDER_CONFIG}
      - MLAT_USER=${MLAT_SITE_NAME}
      - UUID=${ULTRAFEEDER_UUID}
      #
      # --------------------------------------------------
      # TAR1090 (Map Web Page) parameters:
      - UPDATE_TAR1090=true
      - TAR1090_MESSAGERATEINTITLE=true
      - TAR1090_PAGETITLE=${MLAT_SITE_NAME}
      - TAR1090_SITENAME=${MLAT_SITE_NAME}
      - TAR1090_PLANECOUNTINTITLE=true
      - TAR1090_ENABLE_AC_DB=true
      - TAR1090_FLIGHTAWARELINKS=true
      - HEYWHATSTHAT_PANORAMA_ID=${FEEDER_HEYWHATSTHAT_ID}
      - HEYWHATSTHAT_ALTS=${FEEDER_HEYWHATSTHAT_ALTS}
      - TAR1090_SITESHOW=true
      - TAR1090_RANGE_OUTLINE_COLORED_BY_ALTITUDE=true
      - TAR1090_RANGE_OUTLINE_WIDTH=1.5
      - TAR1090_RANGE_OUTLINE_DASH=${TAR1090_RANGE_OUTLINE_DASH}
      - TAR1090_RANGERINGSDISTANCES=${TAR1090_RANGERINGSDISTANCES:-50,100,150,200}
      - TAR1090_RANGERINGSCOLORS='#1A237E','#0D47A1','#42A5F5','#64B5F6'
      - TAR1090_USEROUTEAPI=${FEEDER_TAR1090_USEROUTEAPI}
      - TAR1090_IMAGE_CONFIG_LINK="http://HOSTNAME:${_ADSBIM_STATE_WEBPORT}/"
      - TAR1090_IMAGE_CONFIG_TEXT="ADS-B Feeder Image Configuration"
      # --------------------------------------------------
      # GRAPHS1090 (Decoder and System Status Web Page) parameters:
      # The two 978 related parameters should only be included if you are running dump978 for UAT reception (USA only)
      - GRAPHS1090_REDUCE_IO=true
      - GRAPHS1090_DARKMODE=true
      - ENABLE_978=${FEEDER_ENABLE_UAT978}
      - URL_978=${FEEDER_URL_978}
      #
    volumes:
      - /opt/adsb/config/ultrafeeder/globe_history:/var/globe_history
      - /opt/adsb/config/ultrafeeder/graphs1090:/var/lib/collectd
      - /proc/diskstats:/proc/diskstats:ro
      - /dev:/dev:ro
      - /run/adsb-feeder-ultrafeeder:/run
      - /run/adsb-feeder-shared:/run/airspy_adsb
    tmpfs:
      - /tmp:size=128M
      - /var/log:size=32M
